### ISSUE TITLE
Bug - Portable version can't find ff_hw_dcd.ini

### ISSUE THREAD

**Issue by iG8R** [eibol/ffmpeg_batch#57] opened 2022-12-11 15:38 UTC
Hi.

Windows 10 (21H1, 19043.1415)
FFBatch v2.8.4

Thank you very much for such a useful tool.
When trying to encode from the context menu, an error appears stating that it "`Could not find a part of the path 'C:\User\XXX\AppData\Roaming\FFBatch\ff_hw_dcd.ini'`"

![ffmpeg-batch-av-error-2022-12-11_170138](https://user-images.githubusercontent.com/11407417/206912669-ec6a0bdd-d408-42df-90e5-f4c320d93f9f.jpg)
![ffmpeg-batch-av-error-2022-12-11_165202](https://user-images.githubusercontent.com/11407417/206912676-c1366bca-fa45-41ba-a29e-eadcd0ec1553.jpg)

**Comment by eibol** [comment] 2022-12-12 08:03
Hi, I could not reproduce his issue. 
Can you try refreshing GPU decoders list and restarting?

**Comment by iG8R** [comment] 2022-12-12 20:41
> Can you try refreshing GPU decoders list and restarting?

Sorry, for such a dumb question - where do I have to refresh the GPU decoders list?

**Comment by iG8R** [comment] 2022-12-21 22:26
For the proper work of the portable version with the GPU decoders' option other than `none` it's absolutely necessary to make manually `C:\Users\(username)\AppData\Roaming\` where FFBatch will create the `ff_hw_dcd.ini` file while encoding video. Otherwise, the aforementioned dialog box with an error will appear.

**Comment by 1kari-s** [comment] 2023-01-23 04:55
Good afternoon! Thank you for the wonderful program! Unfortunately I can confirm a similar problem.

**Comment by eibol** [comment] 2023-01-23 11:29
Hi, could you try with this patched version if the issues persists? Thanks
https://drive.upm.es/s/ikJ4YIXKzfaH1ar/download
(copy to your application folder).

**Comment by 1kari-s** [comment] 2023-01-23 14:20
![Bug](https://user-images.githubusercontent.com/123348395/214062282-2b7c117f-b7ca-4406-a556-db2519948c34.jpg)
Unfortunately, it didn't help.

**Comment by 1kari-s** [comment] 2023-01-23 14:21
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.IO.DirectoryNotFoundException: Could not find a part of the path 'D:\Users\1kari\AppData\Roaming\FFBatch\ff_hw_dcd_portable.ini'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalWriteAllText(String path, String contents, Encoding encoding, Boolean checkHost)
   at FFBatch.Form1.btn_mux_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by eibol** [comment] 2023-01-23 17:28
Hi, thanks for the report, I think I found it now.
Patched version at the same link: https://drive.upm.es/s/ikJ4YIXKzfaH1ar/download

**Comment by 1kari-s** [comment] 2023-01-23 18:49
Great! Now it works! Thanks for your hard work!!!

**Comment by 1kari-s** [comment] 2023-01-24 03:55
By the way, another bug is gone. Now works stream multiplex from network sources. Earlier for some reason did not work.
If you can advise how to make that after finishing encoding and closing and opening the program did not save encoding list.

**Comment by eibol** [comment] 2023-01-24 08:55
Great. Regarding saving the encoding list, it is only saved automatically if queue encoding is started and interrupted abnormally, or aborted and then window closed without using the Exit (X) button, just closing the main window.

So if you with to keep the current queue state, you need to use the save queue button, and then doubleclick or load queue file.

**Comment by 1kari-s** [comment] 2023-01-24 09:54
The problem is that the list is always saved. Under all conditions. It always opens files that were opened last time. And I have to clear the list manually. That's never happened before. As far as I remember it started after v2.7.2. Not critical, but it would be nice to fix.

**Comment by eibol** [comment] 2023-01-24 11:17
I can't reproduce your issue, list is always cleared on startup. Anyway, I had hidden any error about that as non-critical.
I have uploaded a new version that should display an error message if it can't delete any temporary queue list file.
https://drive.upm.es/s/ikJ4YIXKzfaH1ar/download

**Comment by 1kari-s** [comment] 2023-01-24 15:23
https://drive.google.com/file/d/1aMd0wvKjMSo72zYpH5unuA28OeGmflpW/view?usp=share_link
Unfortunately, the file you attached does not show anything... Here is an example of how it happens.

**Comment by eibol** [comment] 2023-01-24 15:38
I see, could you just try closing the application using the Exit button?
May I also see a screen capture of your settings?

**Comment by eibol** [comment] 2023-01-26 12:06
You could try this version, it could show more information about the issue. I could reproduce it only once.

**Comment by 1kari-s** [comment] 2023-01-26 12:34
I'm sorry, what version exactly?

**Comment by eibol** [comment] 2023-01-26 12:35
Apologize: https://drive.upm.es/s/ikJ4YIXKzfaH1ar/download

**Comment by 1kari-s** [comment] 2023-01-26 14:20
This is a victory! With the file you attached, the problem is gone! Maybe it's just me, but in general the interface is more responsive. Thank you very much!

**Comment by eibol** [comment] 2023-01-26 16:35
Great, finally. Regarding the responsiveness, I really don't know the possible cause, maybe I changed the .net requirement to 4.7.2.

**Closed** 2023-03-23 10:30 UTC
