### ISSUE TITLE
Burning in subs / using dynamic properties

### ISSUE THREAD

**Issue by vhbert** [eibol/ffmpeg_batch#33] opened 2021-12-21 23:11 UTC
I've been trying to burn in subtitles in an mkv, but I can't seem to get it working to my liking.
I know there is a batch subtitles tab which has the option to burn subtitles, but this seems to be limited to external subtitle files, would it be possible to add the option to use the source file as the source for the subtitles (subs included in the mkv file)?

Since this isn't possible yet, I've tried to manually do this using the following input params.
```
-vf subtitles=%1
```
This throws the following error `Unable to parse option value  "\Users\user\Videos\Kaguya-Sama- Love Is War.S02E05  - GJM.mkv" as image size`

I've then tried adding quotes like this
```
-vf subtitles="%1"
```
But this throws the following `Unable to find a suitable output format for 'Love'`

Not sure if I am missing something or this is just a bug?

**Comment by eibol** [comment] 2021-12-22 10:10
Hi, well, it some sort of bug, but it is related to ffmpeg in Windows and -vf filters breaking file paths, so fo the moment I can't find good solution for this.

I'm thinking that you may use the Stream multiplex tab to save the subtitle as file, and then feed it to the subtitles tab to burn it to the video file, that should work, though it is just a workaround.

**Comment by vhbert** [comment] 2021-12-22 11:14
Sounds like a good workaround for now.
I do wonder though, why does manually running that command work (ffmpeg in the CLI), but running it through the program (with the dynamic property) not?

**Comment by eibol** [comment] 2021-12-22 11:36
It is a combined issue with espaced characters '\' and with windows paths using a drive letter, while the filter expects a unix path without drive letter, starting with just '\'

I have the same issue in command line. 

Are you using Windows command line? Do you have a working command sample?

**Comment by vhbert** [comment] 2021-12-22 12:52
I'm using Command Prompt in the latest Windows Terminal.
Here is the command I used that functions correctly, this command works fine in Powershell as well.
```
ffmpeg -i "Kaguya-Sama- Love Is War.S02E05  - GJM.mkv" -vcodec hevc_nvenc -c:a copy -preset slow -pix_fmt yuv420p10le -crf 20 -x265-params limit-sao:bframes=8:psy-rd=1:aq-mode=3 -map 0 -map -0:s -vf subtitles="Kaguya-Sama- Love Is War.S02E05  - GJM.mkv" out12.mkv

**Comment by eibol** [comment] 2021-12-22 14:30
As I thought, as you have ffmpeg.exe in the same path as source video, you don't have to use path letters or slashes, so it works fine. Looks like a limitation of ffmpeg.
Maybe I coud add a new feature in Batch subtitles, so user can add a video file as subtitles source, so then they are automatically extracted.

**Comment by vhbert** [comment] 2021-12-22 15:00
The ffmpeg exe is not in the same path, a reference is just set to ffmpeg in the windows PATH so it's accessible globally.
This is done by default when installing ffmpeg (I installed it with scoop)

**Comment by eibol** [comment] 2021-12-22 18:48
Well, this gave an idea. I found a way to re-use the source file as subtitles with this dynamic parameter:

`-vf subtitles=%fn.mkv`

For the moment in this test version you need to write the source file extension.
I guess it gets the first subtitle stream to be burned.

You can try it with this [patched executable](https://drive.upm.es/s/ROI1bk9mB5WR7yd/download) version:

**Comment by vhbert** [comment] 2021-12-22 20:25
Thanks for the patched exe. I do seem to get the following error though
` Unable to find a suitable output format for 'on' `
This occurs when just trying to encode using the "Encode" button. (Not the Try preset button).

Maybe I am using the patched exe wrong, do I just need to replace the original exe in the install directory with this new one?

**Comment by eibol** [comment] 2021-12-22 20:54
I see, I've had to create a new dynamic variable for this purpose to wrap spaces internally. 
You could try now with this:

`-vf subtitles=%ff`

New [patched version here](https://drive.upm.es/s/ROI1bk9mB5WR7yd/download). (just replace exe).

**Comment by vhbert** [comment] 2021-12-22 21:47
Getting a new error
```
[Parsed_subtitles_0 @ 000002814ab05140] Unable to open %ff
[AVFilterGraph @ 0000028135e22e80] Error initializing filter 'subtitles' with args '%ff'
```
Seems like the dynamic variable isn't working properly?

**Comment by eibol** [comment] 2021-12-22 22:11
Well, no errors here, trying preset working too. 
Maybe file was not update on the server. 

Uploaded again. Remove your FFbatch.exe and copy [this one](https://drive.upm.es/s/XmkXPEUWO0ldcQs/download).

**Comment by vhbert** [comment] 2021-12-23 10:23
Aha, the updated exe seems to work but the process seems to hang after a few % (about 15-20s)
Can't see anything in the logs either, it just "stops".

Any ideas?

**Comment by eibol** [comment] 2021-12-23 13:14
Sorry, I think I've run out of ideas. I've tried with a two hours video as source, h264 ultrafast, 
and after some initial lag, it encodes fine up to the end.

**Comment by vhbert** [comment] 2021-12-23 13:50
Is there a way to see the current encode "session" in a terminal somehow with the patched exe?
Because atm the "Try on console" button doesn't seem to parse the dynamic variable properly.
Might show me some more details about why the encoding seems to stall.

**Comment by eibol** [comment] 2021-12-23 19:15
Good to know there's a known reason for the problems. Thanks for the information, I'll look into it for next release.
You can disable network caching at settings.

**Comment by vhbert** [comment] 2021-12-23 20:30
Thanks again for your help in resolving my problem.
Keep up the good work in developing this tool, it's very well refined!

**Comment by eibol** [comment] 2022-01-13 18:41
You're welcome

**Comment by bigworld12** [comment] 2022-10-23 11:52
@eibol I am still facing this issue on current version `2.8.2` 
I am doing 
```
-c:v libx264 -crf 23 -vf subtitles=%ff:stream_index=1 -c:a copy -sn -map 0 -map -0:a:1
```
but I get No such file or directory.

**Comment by bigworld12** [comment] 2022-10-23 17:39
after some research, it appears that the correct way to escape characters with absolute path is:
```ps1
$fullName.replace("\", "/\").replace("]", "\]").replace("[", "\[").Replace("\\", "\").replace(":", "\\:")
```

**Comment by eibol** [comment] 2022-10-24 07:04
> 

Hi, I can't reproduce any issue, I've tested those parameters successfully and subtitles are burnt as expected using source file subtitles stream. Whats the

**Comment by ahmednfwela** [comment] 2022-10-24 07:07
@eibol the problem occurs when the path contains ] characters

**Comment by eibol** [comment] 2022-10-24 10:51
I think that removing the conflicting character from source filename on the fly would be the best choice.

**Comment by eibol** [comment] 2022-10-26 12:24
> after some research, it appears that the correct way to escape characters with absolute path is:
> 
> ```powershell
> $fullName.replace("\", "/\").replace("]", "\]").replace("[", "\[").replace("\\", "\").replace(":", "\\:")
> ```

I've tried several escaping and replacing combinations unsuccessfully. I can only rename automatically the source filename replacing any `[ ]`characters by '( )'

**Comment by ahmednfwela** [comment] 2022-10-26 12:30
maybe the app can detect and auto rename invalid chars after asking the user to prevent this scenario ?

**Comment by eibol** [comment] 2022-10-26 12:35
There's no problem with that character in folder name, since filter uses only filename and path is set programatically.
You could test it here, replacing your current FFBatch.exe
[FFBatch.zip](https://github.com/eibol/ffmpeg_batch/files/9869440/FFBatch.zip)

**Comment by ahmednfwela** [comment] 2022-10-26 12:54
I am getting this error

```
Logging for: "[KH] Overlord II - 01 - The Dawn of Despair.mkv"

[Parsed_subtitles_0 @ 0000021043ea33c0] No filename provided!
[AVFilterGraph @ 000002104c18ff80] Error initializing filter 'subtitles' with args ''
Error reinitializing filters!
Failed to inject frame into filter network: Invalid argument
Error while processing the decoded data for stream #0:1
--------End of "[KH] Overlord II - 01 - The Dawn of Despair.mkv" log--------
```
with these args
`-c:v libx264 -crf 18 -vf subtitles=%ff:stream_index=1 -c:a copy -sn -map 0 -map -0:a:0`

**Comment by eibol** [comment] 2022-10-26 13:07
I've tried:
-c:v libx264 -crf 18 -vf "subtitles=%ff:stream_index=1" -c:a copy -sn -map 0 -map -0:a:0

**Comment by ahmednfwela** [comment] 2022-10-26 13:09
@eibol nope:
![image](https://user-images.githubusercontent.com/63286031/198034242-e677dfa7-d3f7-47d3-bc8a-1145b5bc3369.png)

**Comment by eibol** [comment] 2022-10-26 13:25
Can you disable "Try preset" checkmark and try again?

**Comment by ahmednfwela** [comment] 2022-10-26 13:30
Oh it does appear now 
![image](https://user-images.githubusercontent.com/63286031/198038691-9c1d8d1d-92a4-4419-9485-e10c0fb53875.png)

however, it didn't appear when right clicking on an item and then clicking encode

**Comment by ahmednfwela** [comment] 2022-10-26 14:53
apparently `,` and `'` characters in file name also cause the same issue

**Comment by eibol** [comment] 2022-10-27 06:56
Thanks, I've added those characters too. This beta should address the issue:
[FFBatch.zip](https://github.com/eibol/ffmpeg_batch/files/9876536/FFBatch.zip)

**Comment by eibol** [comment] 2022-11-07 08:50
Addressed in new release.

**Closed by eibol** 2022-11-07 08:50 UTC
