### ISSUE TITLE
Enhancement - Multilanguage program GUI

### ISSUE THREAD

**Issue by bovirus** [eibol/ffmpeg_batch#14] opened 2021-06-02 08:17 UTC
@eibol 

Here you can find some info how to make program GUI multilanguage

https://stackoverflow.com/questions/32989100/how-to-make-multi-language-app-in-winforms

**Comment by eibol** [comment] 2021-06-02 16:40
Great, thanks, I'm on it.

**Comment by bovirus** [comment] 2021-06-03 08:23
@eibol

I propose to leave it open because othr users check that you working on it and not open a similar request.

**Comment by eibol** [comment] 2021-06-30 09:10
@bovirus 
Hi, I have finished the localization of most application strings. If you would like to do some translating into intalian, I can send you a resource file with th english strings.

**Comment by bovirus** [comment] 2021-06-30 09:39
@eibol 
It's ok for me
emai: bovirus at gmail dot com

**Comment by eibol** [comment] 2021-06-30 12:21
[Strings.zip](https://github.com/eibol/ffmpeg_batch/files/6740777/Strings.zip)
If you encounter any problem, just let me know.
Thanks

**Comment by bovirus** [comment] 2021-07-25 09:17
@eibol 

Italian language translated at 30%.
[FFMpeg-Batch-AV-Converter-italian-2021.07.23-17.04.15.zip](https://github.com/eibol/ffmpeg_batch/files/6873613/FFMpeg-Batch-AV-Converter-italian-2021.07.23-17.04.15.zip)

What dio you think to dcraete a etst build if it work?

**Comment by eibol** [comment] 2021-07-27 17:53
Hi, I have tested localizatoin with spanish translation and it looks good. 
As soon as you complete it I will pass a few more strings and include the new italian setting so you can verify it.
-

**Comment by eibol** [comment] 2021-08-01 22:02
Hi, I'm releasing the multilanguage version, as soon as you have the italian translation I'll include it for next release.
I'll update the master branch with the new version too.

**Comment by bovirus** [comment] 2021-08-01 22:17
@eibol 

Tomorrow morning you will have italian language files.

**Comment by bovirus** [comment] 2021-08-02 07:53
@eibol 

As promised full translation

[FFMpeg-Batch-AV-Converter-italian-2021.08.02-09.52.21.zip](https://github.com/eibol/ffmpeg_batch/files/6915265/FFMpeg-Batch-AV-Converter-italian-2021.08.02-09.52.21.zip)

If you can please create a test build.

**Comment by eibol** [comment] 2021-08-02 10:56
Great, thanks a lot. I'm releasing the new version as it's been a long time without updates.
I'll start italian integration right now, I'll new a few more strings for user interface, maybe I can get them from the resource files.
I'll keep you posted, I hope in a week or so I can create the italian test build.

**Comment by eibol** [comment] 2021-08-02 11:21
Italian strings integration looks good. I attach the main forms strings, so I can generate the italian test build.
Thanks.
[Form3.txt](https://github.com/eibol/ffmpeg_batch/files/6916465/Form3.txt)
[Form1.txt](https://github.com/eibol/ffmpeg_batch/files/6916466/Form1.txt)

**Comment by eibol** [comment] 2021-08-02 15:19
Concat is concatenación, is an ffmpeg joining filter, did not translate It.
Prest is wrong, I mean prest, Indid not translate that either.

**Comment by eibol** [comment] 2021-08-09 17:24
@bovirus Hi, please find attached the last batch of strings to be translated into italian.
Thanks in advance
[FFB_forms_EN-IT.zip](https://github.com/eibol/ffmpeg_batch/files/6956240/FFB_forms_EN-IT.zip)

**Comment by bovirus** [comment] 2021-08-10 08:27
@eibol 

**_FFB_forms_EN-IT.zip_**
[FFB_forms_EN-IT.zip](https://github.com/eibol/ffmpeg_batch/files/6960129/FFB_forms_EN-IT.zip)

**_Last_strings.txt_**
[Last_strings.txt](https://github.com/eibol/ffmpeg_batch/files/6960134/Last_strings.txt)

Note about FFB_forms_EN-IT.zip

----------------- Form 15.txt

Is "cancel edition" or "cancel edit"?

----------------- Wizard1.tx 

Text is coded as "TIS-620" instead "UTF-8"

Check the character "°"

Ruota di 90ยบ in senso orario
Ruota di 90ยบ in senso antiorario
Ruota di 180ยบ

I converted the etxt file in UTF-8.

What does it mean this string (two times stream and streams)

"Stream copy subtitle streams"

Thanks.

**Comment by eibol** [comment] 2021-08-10 17:16
Many thanks for the translations.

In form15 it is actually "Cancel edition"
Thanks for text encoding warning and correction.

"Stream copy subtitle streams" could be translated into "Copy source subtitles", because if you don't add -c:s copy ffmpeg may convert them to a different format.

**Comment by eibol** [comment] 2021-08-12 14:14
Some remaining UI strings and I could generate a test build for full italian.
Thanks a lot
[Form1_tabs.txt](https://github.com/eibol/ffmpeg_batch/files/6976061/Form1_tabs.txt)

**Comment by bovirus** [comment] 2021-08-13 09:59
@eibol 

Pelase take note of this change

"Stream copy subtitle streams" (eng) is "Copia sottotitoli sorgente"

Attached latest translation resource

[Form1_tabs_ita.txt](https://github.com/eibol/ffmpeg_batch/files/6981554/Form1_tabs_ita.txt)

Thanks.

**Comment by eibol** [comment] 2021-08-15 14:21
@bovirus 

After all the new strings and corrections, please a first test build for italian. I guess some issues will show up.
https://drive.upm.es/index.php/s/Ck2xCKPwEjLk4bX/download

I just realized that default presets names could also be translated, these are the strings:
[Base_presets.txt](https://github.com/eibol/ffmpeg_batch/files/6988276/Base_presets.txt)

Thanks in advance

**Comment by bovirus** [comment] 2021-08-15 17:43
@eilbol

Thanks. It ssmees works fine.
I found only few small issue to fix.
I will post when I'l be back on first week of September.

Preset description in Italian.
[Base_presets_it.txt](https://github.com/eibol/ffmpeg_batch/files/6988575/Base_presets_it.txt)

**Comment by eibol** [comment] 2021-08-15 20:11
@bovirus 

Great, thanks a lot. Enjoy your rest.

**Comment by eibol** [comment] 2021-09-09 14:25
@bovirus 

Hi, I am planning a new release by this week with a few bugfixes.
If you can send to me the translation issues to fix I will include them for this update.
Thanks a lot
Abel

**Comment by bovirus** [comment] 2021-09-11 07:32
@eibol 

I beleieve that v. 2.5.0 already include italian language but is just english/spanish.

I did'n find the exe installer that incldue italian language preview?

Could you please reupload it?

Thanks.

**Comment by eibol** [comment] 2021-09-11 20:46
@bovirus 

Please find [here the latest pre-release](https://drive.upm.es/index.php/s/0eaPTfGbAz1t9BV/download) with some corrections and italian language fully implemented.

**Comment by bovirus** [comment] 2021-09-12 07:28
@eilbol

Some issues.

![FFMpeg batch Converter AV 2 5 2- Installer 01](https://user-images.githubusercontent.com/1262554/132977733-2cf2e424-dd09-4432-978a-1b3452246946.jpg)

![FFMpeg batch Converter AV 2 5 2- Installer 02](https://user-images.githubusercontent.com/1262554/132977734-71e3e9b6-dce4-4cfa-a552-762b83fc9ccb.jpg)

![FFMpeg batch Converter AV 2 5 2 - GUI 01](https://user-images.githubusercontent.com/1262554/132977741-33f5e2dd-fbd0-440d-ab8a-7f43b1b7aa64.jpg)

![FFMpeg batch Converter AV 2 5 2 - GUI 02](https://user-images.githubusercontent.com/1262554/132977742-9a9ec7a3-1eb7-4b8e-8a80-633468dc4afd.jpg)

![FFMpeg batch Converter AV 2 5 2 - GUI 03](https://user-images.githubusercontent.com/1262554/132977743-dd665927-acab-407e-9ace-aeb845154424.jpg)

![FFMpeg batch Converter AV 2 5 2 - GUI 04](https://user-images.githubusercontent.com/1262554/132977745-ed65bbfb-6946-43f1-bbd4-f2e0d5046989.jpg)

![FFMpeg batch Converter AV 2 5 2 - GUI 05](https://user-images.githubusercontent.com/1262554/132977749-4b27824e-5682-4aee-83fb-07694402e8b5.jpg)

![FFMpeg batch Converter AV 2 5 2 - GUI 06](https://user-images.githubusercontent.com/1262554/132977750-96db0e65-e3ea-4bb2-8eb2-376a02cb0c2e.jpg)

![FFMpeg batch Converter AV 2 5 2 - GUI 07](https://user-images.githubusercontent.com/1262554/132977751-65f80b2c-a28f-47d9-bb35-5980af33c409.jpg)

**Comment by eibol** [comment] 2021-09-13 09:31
I have included almost all your fixes and recommendations. The question about some settings text width and so on I'll leave it for next release since it requires a long time.
Thanks a lot for the review.

**Comment by bovirus** [comment] 2021-09-13 14:02
@eibol

Where can i download new version installer 64bit?
If you agree  now I can consider to close this post.
I will open a new ticket if I will make some other feedbacks.

**Comment by eibol** [comment] 2021-09-13 15:11
@bovirus 

You can download the [64 bit pre-release here](https://drive.upm.es/index.php/s/LwnjZVq5g9WUKPO/download).
OK, post can be closed.

**Comment by taozi1996** [comment] 2021-09-27 06:13
Simplified Chinese
I have already translated it.
[cn.zip](https://github.com/eibol/ffmpeg_batch/files/7233814/cn.zip)

**Comment by eibol** [comment] 2021-09-27 08:22
Hi @taozi1996 

Thank you so much for your translation. Those are the gui strings (buttons, etc.).
In order to have all the messages displayed by the application translated, it is also necessary to translate
two resource files. They contain about 1200+ strings, so it can take some time.

If you would like to translate them, I can send to you the english version. 
Thanks a lot.

**Comment by taozi1996** [comment] 2021-09-27 08:24
> Hi @taozi1996
> 
> Thank you so much for your translation. Those are the gui strings (buttons, etc.).
> In order to have all the messages displayed by the application translated, it is also necessary to translate
> two resource files. They contain about 1200+ strings, so it can take some time.
> 
> If you would like to translate them, I can send to you the english version.
> Thanks a lot.

Ok.

**Comment by eibol** [comment] 2021-09-27 08:30
Please find attached the resource files. I've used Visual Studio 2019.
If you need any help just let me know
[Strings_EN_to_CN.zip](https://github.com/eibol/ffmpeg_batch/files/7234624/Strings_EN_to_CN.zip)
.

**Comment by taozi1996** [comment] 2021-09-28 09:00
> Please find attached the resource files. I've used Visual Studio 2019.
> If you need any help just let me know
> [Strings_EN_to_CN.zip](https://github.com/eibol/ffmpeg_batch/files/7234624/Strings_EN_to_CN.zip)
> .
[Strings_cn.zip](https://github.com/eibol/ffmpeg_batch/files/7242579/Strings_cn.zip)

**Comment by eibol** [comment] 2021-09-28 11:21
Thank you very much, I will start with the GUI translation, I hope it is available for next release.

**Comment by eibol** [comment] 2021-10-04 16:12
@taozi1996 

I have finished with the strings and the GUI, I just need the installer custom strings below, and then I can send to you a beta release for you to check and send any corrections you deem necessary.
[Inno_Installer.txt](https://github.com/eibol/ffmpeg_batch/files/7279611/Inno_Installer.txt)
.

**Comment by taozi1996** [comment] 2021-10-05 00:42
> @taozi1996
> 
> I have finished with the strings and the GUI, I just need the installer custom strings below, and then I can send to you a beta release for you to check and send any corrections you deem necessary. [Inno_Installer.txt](https://github.com/eibol/ffmpeg_batch/files/7279611/Inno_Installer.txt) .
[Inno_Installer_cn.txt](https://github.com/eibol/ffmpeg_batch/files/7282030/Inno_Installer_cn.txt)
ok

**Comment by eibol** [comment] 2021-10-05 10:17
Great, I have generated a [test portable build](https://drive.upm.es/s/v4AdvOCoxkufP7x/download) so you can review the translation, any correction or modificacion just let me know.

**Comment by taozi1996** [comment] 2021-10-05 10:57
> Great, I have generated a [test portable build](https://drive.upm.es/s/v4AdvOCoxkufP7x/download) so you can review the translation, any correction or modificacion just let me know.
After installation, start FFBatch,exe  the software will crash. The old version before 2.4 opens normally.
I sent it to others and they also can't start it.

**Comment by eibol** [comment] 2021-10-05 11:05
Apologize, I forgot some new required files. In my computer works fine,
[Test portable build download.](https://drive.upm.es/s/v4AdvOCoxkufP7x/download)

**Comment by taozi1996** [comment] 2021-10-05 11:22
> Apologize, I forgot some new required files. In my computer works fine, [Test portable build download.](https://drive.upm.es/s/v4AdvOCoxkufP7x/download)

I can't open it yet.

**Comment by eibol** [comment] 2021-10-05 12:32
Oh, that's bad.
Any information about the crash error? What is your operating system?

I changed my system to chinese (simplified), and could install and run the application.
![FF_Chinese](https://user-images.githubusercontent.com/907799/136023003-65d78edf-e564-421a-a1d4-4bfaec7ce20a.jpg)

**Comment by taozi1996** [comment] 2021-10-05 13:07
> Oh, that's bad. Any information about the crash error? What is your operating system? Is latest version 2.5.2 running trouble-free?
> 
> I changed my system to chinese (simplified), and could install and run the application. ![FF_Chinese](https://user-images.githubusercontent.com/907799/136023003-65d78edf-e564-421a-a1d4-4bfaec7ce20a.jpg) ![FF_Chinese2](https://user-images.githubusercontent.com/907799/136023211-e970ffc5-c765-4fcd-a754-641c7cfea8bc.jpg)

My system is win10.I also can’t open the 2.5.2 version.I have tried it on different computers.It didn't run.
I sent it to my friends and they can't use it yet.
The problem is both crash.

**Comment by eibol** [comment] 2021-10-05 18:12
This is going to be hard to solve. I have created a Windows 10 virtual machine, set all setttings as Chinese, but still no runtime error. 
Just for diagnostic purposes I have generated this[ beta release](https://drive.upm.es/s/gb3zqPOJaWtaMBw/download), could you try it and let me know the result?
Thanks in advance

**Comment by eibol** [comment] 2021-10-05 21:54
Latest .net runtime version could help: 
https://dotnet.microsoft.com/download/dotnet-framework/net48

**Comment by taozi1996** [comment] 2021-10-06 04:55
> This is going to be hard to solve. I have created a Windows 10 virtual machine, set all setttings as Chinese, but still no runtime error. Just for diagnostic purposes I have generated this[ beta release](https://drive.upm.es/s/gb3zqPOJaWtaMBw/download), could you try it and let me know the result? Thanks in advance
> 
> EDIT: Also for testing purposes, does it make any differente running application as admin?
It didn't run yet.
My computer has already installed .net 4.6.
My computer can run v2.4.2 but can't run v2.5.2 and v2.5.3

**Comment by taozi1996** [comment] 2021-10-06 11:12
> 对不起， 它仍然不工作。我发现了一个传统的中国视窗10版本1809，发现一个错误，现在它运行顺利。
> 
> 由于我不能重现您的问题，我认为找到问题的唯一方法是，我向您发送视觉工作室项目，您安装视觉工作室 2017 或 2019 社区，并尝试在 Debug 模式下编译和运行应用程序。

ok

**Comment by bovirus** [comment] 2021-10-10 21:02
@eibol 

We have to check all strings for both language (included Italian)?

**Comment by bovirus** [comment] 2021-10-11 12:19
@eibol 

Wher can I found current version of Strings2.resx for Italian

Here

https://github.com/eibol/ffmpeg_batch/tree/master/Properties

there is a BR folder.
hy not IT (Italian) folder?

**Comment by eibol** [comment] 2021-11-09 16:52
A few new strings, I roughly translated the
[FF_Strings.zip](https://github.com/eibol/ffmpeg_batch/files/7506588/FF_Strings.zip)
[Resource_strings.zip](https://github.com/eibol/ffmpeg_batch/files/7506589/Resource_strings.zip)
m.

**Comment by bovirus** [comment] 2021-11-16 13:47
@eilbol

Sorry for the delay.

[Italian.zip](https://github.com/eibol/ffmpeg_batch/files/7546772/Italian.zip)

**Comment by eibol** [comment] 2021-11-16 19:38
Thanks, all merged for next release.
No more translations expected in the near future, I close the issue.
Cheers

**Closed** 2021-11-16 19:39 UTC
